### ISSUE TITLE
doesnt work on mac cause of standard_paths not supporting mac

### ISSUE THREAD

**Issue by solnyszczko** [lifescapegame/lifescape#206]
Tried to compile on my mac, didnt work due to the dependency "standard_paths" not supporting macos

```
   Compiling standard_paths v2.1.0
error[E0599]: no method named `writable_location_impl` found for reference `&StandardPaths` in the current scope
   --> /Users/kisaczka/.cargo/registry/src/index.crates.io-6f17d22bba15001f/standard_paths-2.1.0/src/lib.rs:210:14
    |
210 |         self.writable_location_impl(location)
    |              ^^^^^^^^^^^^^^^^^^^^^^ help: there is a method with a similar name: `writable_location`

error[E0599]: no method named `standard_locations_impl` found for reference `&StandardPaths` in the current scope
   --> /Users/kisaczka/.cargo/registry/src/index.crates.io-6f17d22bba15001f/standard_paths-2.1.0/src/lib.rs:225:14
    |
225 |         self.standard_locations_impl(location)
    |              ^^^^^^^^^^^^^^^^^^^^^^^ help: there is a method with a similar name: `standard_locations`

error[E0425]: cannot find function `find_executable_in_paths_impl` in this scope
   --> /Users/kisaczka/.cargo/registry/src/index.crates.io-6f17d22bba15001f/standard_paths-2.1.0/src/lib.rs:274:9
    |
274 |         find_executable_in_paths_impl(name, &paths)
    |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ not found in this scope

Some errors have detailed explanations: E0425, E0599.
For more information about an error, try `rustc --explain E0425`.
error: could not compile `standard_paths` (lib) due to 3 previous e

```

**Comment by Shatur** [comment]
Thanks!
I would contribute to `standard_paths`, but I'm not familiar with macos. So I probably should find another library.

The game itself is not playable right now, but I'm working on it to make at least minimal game loop.

**Comment by solnyszczko** [comment]
Sadly I am not very familiar with MacOS either, so i cant contribute ;w;

Yeah just wanted to see what the replicon author was up to ! I am currently looking at the examples and trying to do some fun stuff with them

**Comment by Shatur** [comment]
Fixed it, but I wouldn't recommend to try the game for now :smile:

**Comment by solnyszczko** [comment]
> Fixed it, but I wouldn't recommend to try the game for now 😄

Hehe well I tried it anyway, this time it did compile and I played it as much as i could, seems everything works- i walked around and placed down some stuff.

P.S.
this is gonna be annoying, but i just want to say i hope one day replicon has wasm client support :DDDDDDD

**Comment by Shatur** [comment]
>  this is gonna be annoying, but i just want to say i hope one day replicon has wasm client support :DDDDDDD

To achieve this you need these two PRs to be merged:
https://github.com/lucaspoffo/renet/pull/119
https://github.com/lucaspoffo/renet/pull/107
But Renet author is currently busy/

**Comment by solnyszczko** [comment]
Awesome ! Can't wait.
